config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tickets#index'
  get '/index', to: 'index#something'
  get '/output', to: 'index#something2'
  get '/openfile', to: 'index#something3'
  resources :tickets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  enum ticket_status: [ :active, :archived, :pending ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception, :except => [:create, :index, :update, :new, :edit]
  # skip_before_action :verify_authenticity_token
  # protect_from_forgery
  # skip_before_action :verify_authenticity_token
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def something
    redirect_to(params[:url])
  end

  def something2
    @text = params[:text]
  end

  def something3
    file = params[:file]
    File.open(file, "r") {|f|
      # f.flock(File::LOCK_SH)
      # logger.debug (f.read)
      t = f.read
      logger.debug (t)
      @output = t
    }
    render 'something2'
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:name, :ticket_status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/index/something2.html.erb
<p id="notice"><%= notice %></p>

<h1>Something2</h1>

<%= sanitize(@text) %>

<%= @output %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CybersecurityMoocP1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <a href='/index?url=http://cnn.com'>XSS 1</a>
    <a href='/output?text=YOURTEXT'>XSS 2</a>
    <a href='/output?text=<a href=xxxxx>xxxx</a>'</a>XSS 3</a>
    <a href='/tickets'>To your tickets</a>
    <a href='/openfile?file=/etc/passwd'>file inclusion</a>


    <%= yield %>
  </body>
</html>

app/views/tickets/_form.html.erb
<%= form_for(ticket) do |f| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_area :name %>
  </div>

  <div class="field">
    <%= f.label :ticket_status %>
    <%= f.select(:ticket_status, Ticket.ticket_statuses.keys.map {|stat| [stat.titleize,stat]}) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ticket status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <%# <% full_sanitizer = Rails::Html::FullSanitizer.new %> %>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= sanitize(ticket.name) %></td>
        <td><%= ticket.ticket_status %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= sanitize(@ticket.name) %>
</p>

<p>
  <strong>Ticket status:</strong>
  <%= @ticket.ticket_status %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>